PLUGINRANGERS-327 | Trigger the Prestashop Validator (#415)
* feat: First attempt to trigger the Prestashop Validator

* feat: Test #2

* refactor: Total refactor, manual send, test #3

* chore: Test #4

* chore: Test #5

* chore: Test #6

* chore: Test n7

* chore: Removed v2 from action name

diff --git a/.github/workflows/prestashop-validator.yml b/.github/workflows/prestashop-validator.yml
--- a/.github/workflows/prestashop-validator.yml
+++ b/.github/workflows/prestashop-validator.yml
@@ -1,20 +1,28 @@
-name: Prestashop validator
-on: [push, pull_request]
+name: PrestaShop Validator
+on: [push]
+
 jobs:
   prestashop-validator:
-    name: Build & Send to validator
     runs-on: ubuntu-latest
+
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Create temporal tag
-        run: git tag ci
-
-      - name: Build
-        run: sh build.sh ci
-
-      - name: Send to validator API
+      - name: Validate module via GitHub branch
         env:
-            VALIDATOR_API_KEY: ${{ secrets.PRESTASHOP_VALIDATOR_API_KEY }}
-        run: bash ./.github/scripts/validate-prestashop.sh
+          PS_VALIDATOR_KEY: ${{ secrets.PRESTASHOP_VALIDATOR_API_KEY }}
+        run: |
+          RESPONSE=$(curl -s -X POST https://validator.prestashop.com/api/modules \
+            -F "github_link=${{ github.repository }}" \
+            -F "github_branch=${{ github.ref_name }}" \
+            -F "key=$PS_VALIDATOR_KEY")
+
+          echo "$RESPONSE"
+
+          ERRORS=$(echo "$RESPONSE" | jq '.Details.results.errors // 0')
+
+          # Since we are validating from the branch we will always get at least one error.
+          if [ "$ERRORS" -gt 1 ]; then
+            echo "❌ Validator found $((ERRORS - 1)) error/s"
+            exit 1
+          fi
+
+          echo "✅ Module passed validation"
